# Generated by Django 6.0.5 on 2026-05-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udempy', '0003_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='TEST', max_length=100),
            preserve_default=False,
        ),
    ]
